Repository tnb-software/TNB, pull requests merged in 2022-11, with the labels that each got.

#229 management of global wide dependencies related also to performance systems
  pom.xml
  system-x/services/horreum/pom.xml
  system-x/services/hyperfoil/pom.xml
  system-x/services/hyperfoil/src/main/java/software/tnb/hyperfoil/validation/HyperfoilValidation.java
  system-x/services/prometheus-metrics/pom.xml
  system-x/services/webhook/pom.xml
Labels: approved

#233 🔧 Add property for CSB Example repository
  fuse-products/src/main/java/software/tnb/product/csb/configuration/SpringBootConfiguration.java
Labels: approved

#232 ✨ Make Telegram Bot API deployable on OCP
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/TelegramBotAPIContainer.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/local/LocalTelegramBotAPI.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/local/TelegramBotAPIContainer.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/openshift/OpenshiftTelegramBotAPI.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/service/TelegramBotApi.java
Labels: approved, commented

#240 [Changelog] Select only v* tags in changelog
  .github/workflows/release.yml
Labels: approved

#242 [Google] Expose functions region in account
  system-x/services/google/cloud/functions/src/main/java/software/tnb/google/cloud/functions/account/GoogleFunctionsAccount.java
  system-x/services/google/cloud/functions/src/main/java/software/tnb/google/cloud/functions/service/GoogleFunctions.java
  system-x/services/google/cloud/functions/src/main/java/software/tnb/google/cloud/functions/validation/GoogleFunctionsValidation.java
Labels: approved

#241 [Webhook] Share the created webhook endpoint by default
  system-x/services/webhook/src/main/java/software/tnb/webhook/service/Webhook.java
  system-x/services/webhook/src/main/java/software/tnb/webhook/validation/WebhookValidation.java
Labels: review-requested, approved

#248 Fix failing bucket creation on minio by adding forcePathStyle to s3 client
  system-x/services/aws/s3/src/main/java/software/tnb/aws/s3/service/Minio.java
Labels: approved

#237 [plugin] Add support for plugins
  fuse-products/src/main/java/software/tnb/product/application/App.java
  fuse-products/src/main/java/software/tnb/product/cq/application/QuarkusApp.java
  fuse-products/src/main/java/software/tnb/product/csb/application/SpringBootApp.java
  fuse-products/src/main/java/software/tnb/product/integration/builder/AbstractIntegrationBuilder.java
  fuse-products/src/main/java/software/tnb/product/util/maven/Maven.java
Labels: approved

#251 ⬆️ Use camel 3.18
  fuse-products/pom.xml
Labels: approved

#249 [fix] Resources copy for OCP
  fuse-products/src/main/java/software/tnb/product/deploystrategy/OpenshiftBaseDeployer.java
  fuse-products/src/main/java/software/tnb/product/integration/Resource.java
Labels: approved, commented

#252 Add Telegram client for Openshift
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/TelegramContainer.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/local/LocalTelegram.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/local/TelegramClientContainer.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/openshift/OpenshiftTelegram.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/service/Telegram.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/validation/TelegramValidation.java
Labels: approved, commented

#259 Fix telegram Openshift client
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/openshift/OpenshiftTelegram.java
Labels: approved

#261 [Actions] Add dependency diff action
  .github/workflows/dependencies-diff.yml
  .github/workflows/release-snapshot.yml
Labels: approved

#266 ⬆️ Upgrade ES docker image version
  system-x/services/elasticsearch/src/main/java/software/tnb/elasticsearch/service/Elasticsearch.java
Labels: approved

#267 Log to unique file every time
  common/src/main/resources/log4j2.xml
Labels: approved

#269 [Telegram] Fix autoservice definition
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/local/LocalTelegram.java
  system-x/services/telegram/src/main/java/software/tnb/telegram/resource/openshift/OpenshiftTelegram.java
Labels: approved

#271 ServiceFactory can instance concrete classes if they are instanceable
  system-x/common/src/main/java/software/tnb/common/service/ServiceFactory.java
Labels: approved

#272 Improve ServiceFactory error handling
  system-x/common/src/main/java/software/tnb/common/service/ServiceFactory.java
Labels: approved

#270 [SystemX] Move classes into correct packages
  system-x/services/horreum/src/main/java/software/tnb/horreum/configuration/HorreumConfiguration.java
  system-x/services/horreum/src/main/java/software/tnb/horreum/validation/HorreumValidation.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/local/AMQBrokerContainer.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/local/LocalAMQBroker.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/OpenshiftAMQBroker.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Acceptor.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/ActiveMQArtemis.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/ActiveMQArtemisList.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/ActiveMQArtemisSpec.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/ActiveMQArtemisStatus.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/AddressSetting.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/AddressSettings.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Connector.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Console.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/DeploymentPlan.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Limits.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/PodStatus.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Requests.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Resources.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Storage.java
  system-x/services/jms/amq/src/main/java/software/tnb/jms/amq/resource/openshift/generated/Upgrades.java
  system-x/services/splunk/src/main/java/software/tnb/splunk/resource/local/LocalSplunk.java
  system-x/services/splunk/src/main/java/software/tnb/splunk/resource/local/SplunkContainer.java
  system-x/services/splunk/src/main/java/software/tnb/splunk/resource/openshift/OpenshiftSplunk.java
Labels: approved

#273 ✨ Add binary s2i OCP deploy strategy
  fuse-products/src/main/java/software/tnb/product/deploystrategy/OpenshiftDeployStrategyType.java
  fuse-products/src/main/java/software/tnb/product/deploystrategy/impl/BinaryStrategy.java
Labels: approved
